apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
  name: phpmyadmin
spec:
  type: LoadBalancer
  selector:
    app: phpmyadmin
  ports:
  - port: 5000
    targetPort: 5000
    name: phpmyadmin
    protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deploy
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: image-phpmyadmin
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /bin/ash
            - -c
            - 'pgrep php-fpm && pgrep nginx'
          initialDelaySeconds: 3
          periodSeconds: 3
        ports:
        - containerPort: 5000