apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
  name: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 80
  - port: 443
    name: https
    protocol: TCP
    targetPort: 443
  - port: 22
    name: ssh
    targetPort : 22
    protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: image-nginx
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /bin/ash
            - -c
            - 'pgrep nginx && pgrep sshd'
          initialDelaySeconds: 3
          periodSeconds: 3
        ports:
          - containerPort: 80
            name: http
          - containerPort: 443
            name: https
          - containerPort: 22
            name: ssh