apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deploy
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: image-ftps #name of the docker image #nginx:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /bin/ash
            - -c
            - 'pgrep vsftpd'
          initialDelaySeconds: 3
          periodSeconds: 3
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 21101
        - containerPort: 21100
---
apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
  - port: 20
    name: ftps-data
    targetPort: 20
    protocol: TCP
  - port : 21
    name: ftps
    targetPort: 21
    protocol: TCP
  - port: 21101
    name: ftps-psv1
    targetPort: 21101
    protocol: TCP
  - port: 21100
    name: ftps-psv2
    targetPort: 21100
    protocol: TCP